site_name: ErgoDocs
site_url: https://ergodocs.rtfd.io
repo_url: https://github.com/glasgowm148/ergodocs


theme:
    name: material
    favicon: assets/favicon.png
    palette: # dark scheme toggle on material + dark orange
      - scheme: default
        primary: red
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - scheme: slate
        primary: red
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    features:
        - navigation.tabs.sticky
        - navigation.instant
        - navigation.sections # The bold sections in navigation
        - navigation.tracking
        - navigation.indexes
      #  - toc.integrate
    logo: assets/logo.png
    font:
      text: Roboto
extra_css: [assets/extra.css]

extra:
  version:
    provider: mike


extra:
  generator: false


plugins:
  - search

markdown_extensions:
  - meta
  - admonition

nav:
  - Getting Started:
    - Getting Started: index.md
    - Contributing: contribute.md
    - FAQ: faq.md
    - Events: events.md

  - Developers:
    - Developers: dev/index.md
    - Protocol: 
      - Protocol: dev/protocol/index.md
      - UTXO State: dev/protocol/utxo-state.md
      - Autolykos: dev/protocol/autolykos.md
      - Storage Rent: dev/protocol/rent.md
      - NIPoPoWS: dev/protocol/nipopow.md
    - Data Model:
      - Transactions: dev/protocol/transaction.md
      - Box: dev/data-model/box.md
      - Block: dev/data-model/block.md
    - Wallets:
      - Addresses: dev/wallet/address.md
      - Hierarchical keys: dev/wallet/keys.md
    - Smart Contracts:
      - Smart Contracts: dev/scs/index.md
      - ErgoScript: dev/scs/ergoscript.md
      - FlowCards: dev/scs/flowcards.md
      - Sigma Protocols: dev/scs/sigma.md
      - Multi-Stage Contracts: dev/scs/multi.md 
    - P2P:
      - P2P: dev/p2p/index.md
      - Handshaking: dev/p2p/p2p-handshake.md
      - Network Messages: dev/p2p/network.md
      - Modifiers Exchange: dev/p2p/modifiers.md
     # - BlockP2P: dev/p2p/BlockP2P.md
    
    - Resources: 
      - Misc: dev/start/resources.md
      - Libraries:
        - AppKit: dev/stack/appkit.md
        - ErgoTool: dev/stack/ergotool.md
        - Kiosk: dev/stack/kiosk.md
        - JDE: dev/stack/jde.md
        - Assembler: dev/stack/assembler.md
      - Languages:
        - Scala: dev/Languages/scala.md
        - Java: dev/Languages/java.md
        - Rust: dev/Languages/rust.md
        - C#: dev/Languages/csharp.md
      - Stack: 
        - Front-End: dev/stack/front-end.md
        - Back-End: dev/stack/back-end.md
      - Integration: dev/Integration/guide.md 

  - Node:
    - Node: node/index.md
    - Overview: 
      - Swagger API: node/swagger.md
      - Architecture: node/architecture.md
      - Distributed Signatures: node/sigs.md
    - Light Modes: 
      - Digest State: node/digest-state.md
      - History Pruning: node/history-pruning.md
      - Snapshots: node/snapshots.md
      - NiPoPoWS: node/nipopow.md

  - Applications:
    - Applications: uses/index.md
    - Live dApps:
      - Decentralised Exchanges: uses/dex.md
      - Stablecoins: uses/stablecoins.md
      - Oracles: uses/oracles.md
      - NFTs: uses/nft.md
    - In Development:
      - ICOs: uses/ico.md
      - Index Coins: uses/index_coins.md
      - Lending: uses/lending.md
      - CrowdFunding: dev/scs/crowdfunding.md
      - Zero-Knowledge: uses/zk.md      
      - Email Client for Blocked Internet: uses/blocked_web.md
    - Planned:
      - Asset Tokenisation: uses/tokenisation.md
      - DAO: uses/dao.md
      - Buy Back Guarantees: uses/dex-buyback.md
      - LETS: uses/lets.md
      - Atomic Swaps: dev/protocol/atomic.md
    - Further Ideas:
      - CDBC: uses/cdbc.md
      - Lotteries: uses/lottery.md
      - Insurance: uses/insurance.md
      - Derivatives: uses/deriv.md
      - Yield Aggregation: uses/yield.md
      - Micro Credit: dev/scs/microcredit.md
      - Math Fun: uses/math_fun.md
      - PoW Tokens: uses/PoW_tokens.md
      - Collateral Mining: uses/collateral-mining.md
      - Perpetual Tokens: uses/perpetual.md
      - Bonding Curve: uses/bonding.md


      




