site_name: ErgoDocs
site_url: https://ergodocs.rtfd.io

theme:
    name: readthedocs

nav:
    - Home: index.md
    - Tutorials: tutorials.md
    - How-to Guides: howto.md
    - Explanations: explanations.md
    - References: references.md