site_name: ErgoDocs
site_url: https://docs.ergoplatform.com
repo_url: https://github.com/glasgowm148/ergodocs
edit_uri: edit/main/docs/


theme:
    name: material
    favicon: assets/favicon.png
    palette: # dark scheme toggle on material + dark orange
      - scheme: slate
        primary: red
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - scheme: default
        primary: red
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    features:
        - navigation.tabs.sticky
        - navigation.instant
        - navigation.sections # The bold sections in navigation
        - navigation.tracking
        - navigation.indexes
      #  - toc.integrate
    logo: assets/logo.png
    font:
      text: Roboto
extra_css: [assets/extra.css]
extra_javascript:
  - assets/extra.js


extra:
  version:
    provider: mike


extra:
  generator: false


plugins:
  - search

markdown_extensions:
  - meta
  - admonition

nav:
  - Getting Started:
    - Getting Started: index.md
    - Contributing: contribute.md
    - FAQ: faq.md
    - Events: 
      - Events: events/index.md
      - ERGOHACK: events/ergohack.md
      - ErgoSummit: events/ergosummit.md
  - Developers:
    - Developers: dev/index.md
    - Protocol: 
      - Protocol: dev/protocol/index.md
      - Components: 
        - eUTXO: dev/protocol/eutxo.md
        - Autolykos: dev/protocol/autolykos.md
        - Storage Rent: dev/protocol/rent.md
        - NIPoPoWS: dev/protocol/nipopow.md
      - Scaling: dev/protocol/scaling.md
      - EIPs: dev/protocol/eip.md
    - Data Model:
      - Transactions: dev/protocol/transaction.md
      - Box: dev/data-model/box.md
      - Block: dev/data-model/block.md
    - Wallets:
      - Wallets: dev/wallet/index.md
      - Addresses: dev/wallet/address.md
      - Hierarchical keys: dev/wallet/keys.md
      - Payments:
        - ErgoPay: dev/wallet/payments/ergo-pay.md
        - dApp Connector: dev/wallet/payments/dApp.md
        - Ledger: dev/wallet/payments/ledger.md
    - Smart Contracts:
      - Smart Contracts: dev/scs/index.md
      - ErgoScript: 
        - Overview: dev/scs/ergoscript.md
        - Quick Primer: dev/scs/ergoscript-primer.md
        - Sigma Language: dev/scs/sigma-lang.md
      - FlowCards: dev/scs/flowcards.md
      - Sigma Protocols: dev/scs/sigma.md
      - Multi-Stage Contracts: dev/scs/multi.md 
    - P2P:
      - P2P: dev/p2p/index.md
      - Handshaking: dev/p2p/p2p-handshake.md
      - Network Messages: dev/p2p/network.md
      - Modifiers Exchange: dev/p2p/modifiers.md
     # - BlockP2P: dev/p2p/BlockP2P.md
    - Resources: 
      - Libraries:
        - AppKit: dev/resources/lib/appkit.md 
        - ErgoTool: dev/resources/lib/ergotool.md
        - Kiosk: dev/resources/lib/kiosk.md
        - JDE: dev/resources/lib/jde.md
        - Assembler: dev/resources/lib/assembler.md
      - Languages:
        - Scala: dev/resources/lang/scala.md 
        - Java: dev/resources/lang/java.md
        - Rust: dev/resources/lang/rust.md
        - C#: dev/resources/lang/csharp.md
      - Stack: 
        - Front-End: dev/resources/stack/front-end.md 
        - Back-End: dev/resources/stack/back-end.md
      - Tutorials:
       #- Dust: node/dust.md
        - Pi Blockchain Explorer: dev/stack/rpi-blockchain-explorer.md
      - Integration: dev/Integration/guide.md
      - Misc: 
        - Bookmarks: dev/start/resources.md
        - Test-net: dev/start/testnet.md


  - Node:
    - Node: node/index.md
    - Getting Started: 
      - Platforms: node/platforms/index.md
      - Mac: node/platforms/mac.md
      - Windows: node/platforms/windows.md
      - Linux: node/platforms/linux.md
      - Pi: node/platforms/pi.md
      - Docker: node/platforms/docker.md
      - Troubleshooting: node/platforms/troubleshooting.md 
      - FAQ: node/platforms/FAQ.md 
    #- Quick Install: node/quick.md
    - Overview: 
      - Wallet: node/wallet.md
      - Swagger API: node/swagger.md
      - Architecture: node/architecture.md
      - Distributed Signatures: node/sigs.md
    - Light Modes: 
      - Digest State: node/digest-state.md
      - History Pruning: node/history-pruning.md
      - Snapshots: node/snapshots.md
      - NiPoPoWS: dev/protocol/nipopow.md

  - Applications:
    - Applications: uses/index.md
    - Live dApps:
      - Decentralised Exchanges: uses/dex.md
      - Stablecoins: uses/stablecoins.md
      - Oracles: uses/oracles.md
      - NFTs: uses/nft.md
      - ErgoMixer: uses/mixer.md
      - CrowdFunding: uses/crowdfunding.md
      - Zero-Knowledge: uses/zk.md
    - In Development:
      - ProfitSharing: uses/profit.md
      - ICOs: uses/ico.md
      - Index Coins: uses/index_coins.md
      - Lending: uses/lending.md
      - DAO: uses/dao.md     
    - Planned:
      - Asset Tokenisation: uses/tokenisation.md
      - Buy Back Guarantees: uses/dex-buyback.md
      - LETS: uses/lets.md
      - Email Client for Blocked Internet: uses/blocked_web.md
      - Atomic Swaps: dev/protocol/atomic.md
      - ErgoData: uses/ErgoData.md
    - Further Ideas:
      - CDBC: uses/cbdc.md
      - Lotteries: uses/lottery.md
      - Insurance: uses/insurance.md
      - Derivatives: uses/deriv.md
      - Yield Aggregation: uses/yield.md
      - Micro Credit: dev/scs/microcredit.md
      - Math Fun: uses/math_fun.md
      - PoW Tokens: uses/PoW_tokens.md
      - Collateral Mining: uses/collateral-mining.md
      - Perpetual Tokens: uses/perpetual.md
      - Bonding Curve: uses/bonding.md


      




